# API
FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
COPY apps/api/package*.json ./

RUN npm install

COPY apps/api ./

RUN npx prisma generate && npm run build

EXPOSE 3001

CMD ["npm", "start"]